### ISSUE TITLE
Progress / Questions

### ISSUE THREAD

**Issue by stoeckel4code** [VACILT/student_project#2]
I tried to use the function by scipy to implement the stouffer's method. unfortunately I had no success with itm that's why I used the assign()-function to get a nem var. I confused the stouffer's method with the fishers method, but that’s fixed quickly. My question is: Is this the way to go on, or shall i use the build-in function? All in all, it seems to be working.

**Comment by stoeckel4code** [comment]
I tried the stouffers z-score to calculate the combined p-values using

![image](https://user-images.githubusercontent.com/58188931/73961583-2efdaa00-490d-11ea-9490-6170a936f9b4.png) by [Wikipedia](https://en.wikipedia.org/wiki/Fisher%27s_method)

I need the Zi = Φ − 1(1−pi) but doen't know how to code it.

Using the scipy.stats.combine_pvalues funtions isn't possibel, because it needs a 1D-array and I want to calculate it for every dimension.

**Comment by stoeckel4code** [comment]
I got the combined p-value working, using your funktion ([here](https://github.com/VACILT/student_project/blob/95f6d26ba57d0b2cf8cfc45eccefc95bb01c0fe5/hvplot_automatically.py#L76)). All in all is everything working.

Two smaller problems remain:

1.) I dont know how to change the color of the plot
2.) The colar scale has fixed values set (-40 to 40) but some values are higher/lower

**Comment by kuchaale** [comment]
```python
temp = ds_mean['coefs'].hvplot.quadmesh('x','y', cmap = 'RdBu_r', colorbar = True, logy=True, ylim=(1000,0.1))) 
temp.options(symmetric=True) #, vmax = 40, vmin = -40
```

**Comment by stoeckel4code** [comment]
Problems 1.) and 2.) solved by standardizing all values.

**Comment by kuchaale** [comment]
Then please close it.
