### ISSUE TITLE
Prepare Binder repository

### ISSUE THREAD

**Issue by kuchaale** [VACILT/student_project#6]
Try to get familiar with [Binder](https://mybinder.readthedocs.io/en/latest/introduction.html) and prepare the repository so that final notebooks can be replicable using Binder. I would like to follow ["Ten Simple Rules for Writing and Sharing Computational Analyses in Jupyter Notebooks"](https://github.com/jupyter-guide/ten-rules-jupyter) as much as we can.

**Comment by stoeckel4code** [comment]
I initialized the Binder repository with an environment file, but it struggles to load the following packages:
- glob
- scipy.stats
- hvplot.xarray

**Comment by kuchaale** [comment]
Try to specify e.g. [conda-forge channels](https://mybinder.readthedocs.io/en/latest/tutorials/reproducibility.html#pin-dependencies) as `hvplot` installs from the pyviz channel.

**Comment by stoeckel4code** [comment]
Binder works fine for the ROI-drawer. For the other files I may have to expand the [environment.yml](https://github.com/VACILT/student_project/blob/master/environment.yml)

**Comment by stoeckel4code** [comment]
https://mybinder.org/v2/gh/VACILT/student_project.git/master works also for [Combined.ipynb](https://hub.gke.mybinder.org/user/vacilt-student_project-6egjgerl/notebooks/Combined.ipynb)

**Comment by kuchaale** [comment]
It works smoothly and allows to test your progress. Well done. I would recommend building the Binder badge (see [here](https://github.com/jupyterhub/binder/blob/master/doc/howto/badges.rst)) and then close the issue. Do you agree?

**Comment by stoeckel4code** [comment]
ok, I added the badge to the [README.md](https://github.com/VACILT/student_project/edit/master/README.md) and close the issue.
