### ISSUE TITLE
Import data

### ISSUE THREAD

**Issue by kuchaale** [VACILT/student_project#7]
Related to #6. See options [here](https://github.com/binder-examples/getting-data) or below

- [with Quilt](https://mybinder.readthedocs.io/en/latest/sample_repos.html#importing-data-with-quilt)
- locally in Github
- downloadable via wget from somewhere (e.g. [Mendeleye data](https://data.mendeley.com/))
- develop [catalog](https://github.com/intake/intake-xarray/blob/master/examples/catalog.yml) of netcdf files to be importable using [intake-xarray](https://render.githubusercontent.com/view/ipynb?commit=597e907cb561a77ebc548e235aaddfd48dd78c8a&enc_url=68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f696e74616b652f696e74616b652d7861727261792f353937653930376362353631613737656263353438653233356161646466643438646437386338612f6578616d706c65732f696e74616b655f7861727261792e6970796e62&nwo=intake%2Fintake-xarray&path=examples%2Fintake_xarray.ipynb&repository_id=126982453&repository_type=Repository#Catalog-examples), the data should be uploaded somewhere anyway
- other options?

**Comment by stoeckel4code** [comment]
I have uploaded the the data locally to Github and it works.
