### ISSUE TITLE
Project presentation

### ISSUE THREAD

**Issue by kuchaale** [VACILT/student_project#8]
I suggest agreeing on a form of project presentation and potentially date of occurrence. In these days there are only two options: active or passive way of remote presentation. The passive way may be represented by a screencast video, short paper or blogpost. I personally vote for the active way using a live webstream (e.g. Youtube) which could include interactions with interested colleagues at LIM and it would not be so time-consuming for you. In the end, a part of the video recorded may be used for an ex-post presentation.

The presentation should include a few slides covering project motivation and goals, tools and data used, what you have learnt, future outlook, and the prototype presentation itself. What do you think?

**Comment by stoeckel4code** [comment]
I would prefer the passive way, because my english isn't very safe. I will finish the tap plot and add some widgets so the ROI-drawer and then start making the presentation. ok?
